name: islamic
description: A new Flutter project.
publish_to: 'none'
version: 1.5.2+10

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  android_intent: ^2.0.2
  appsflyer_sdk: ^6.2.4+4-nullsafety
  archive: ^3.1.2
  audio_service: ^0.17.1
  autocomplete_textfield_ns: ^2.0.0
  crypto: ^3.0.1
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_messaging: ^10.0.2
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^3.0.5
  flutter_svg: ^0.22.0
  flutter_widget_from_html_core: ^0.6.1
  in_app_review: ^2.0.2
  intl: ^0.17.0
  just_audio: ^0.7.5
  package_info: ^2.0.2
  path_provider: ^2.0.2
  rive: ^0.7.20
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  smartlook: ^2.0.1
  timezone: ^0.7.0
  wakelock: ^0.5.2
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - texts/
    - anims/

  fonts:
    - family: mequran
      fonts:
        - asset: fonts/me_quran.ttf
    - family: scheherazade
      fonts:
        - asset: fonts/scheherazade.ttf
    - family: CubicSans
      fonts:
        - asset: fonts/cubicsans_regular.ttf
    - family: Titles
      fonts:
        - asset: fonts/titles.ttf