name: islamic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rive: ^0.7.3
  intl: ^0.17.0
  share: ^2.0.1
  crypto: ^3.0.1
  archive: ^3.1.2
  timezone: ^0.7.0
  just_audio: ^0.7.0
  path_provider: ^2.0.1
  firebase_core: ^1.0.4
  in_app_review: ^2.0.2
  audio_service: ^0.17.0
  android_intent: ^2.0.0
  # package_info: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^3.0.5
  firebase_analytics: ^8.0.1
  firebase_messaging: ^9.1.2
  shared_preferences: ^2.0.5
  cached_network_image: ^3.0.0
  autocomplete_textfield_ns: ^2.0.0
  flutter_svg: ^0.20.0-nullsafety.1
  appsflyer_sdk: ^6.2.4+4-nullsafety
  flutter_widget_from_html_core: ^0.6.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/
    - texts/
    - anims/
    - locs/

  fonts:
    - family: mequran
      fonts:
        - asset: fonts/me_quran.ttf
    - family: scheherazade
      fonts:
        - asset: fonts/scheherazade.ttf
    - family: CubicSans
      fonts:
        - asset: fonts/cubicsans-regular.ttf
    - family: Titles
      fonts:
        - asset: fonts/titles.ttf